pub mod vectors_objects_different_types;
pub mod why_dynamic_dispatch;
pub mod dynamic_dispatch;
pub mod static_dispatch;
pub mod operator_overloading;
pub mod drop;
pub mod into;
pub mod parameters;
pub mod basic;